### ISSUE TITLE
Scoping CHS jsPsych studies

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-api#1324]
This issue is to track the multiple smaller issues that will need to be implemented in order to introduce support for jsPsych studies on CHS, and to manage the prioritization of optional/'nice to have' features over time and/or release phases.

# jsPsych phase 1 MVP

## Feature implementation:

This is the list of minimum requirements for the initial 'phase 1' release of jsPsych study support:

- [ ] Add jsPsych to study types: #1262
- [ ] Add jsPsych views and URLs for study participation/preview: #1262
- [ ] Send jsPsych data to lookit-api via response API and mark completed responses (using custom Lookit version of `initJsPsych`): #1282, #1283, #1262
- [ ] Redirect jsPsych studies to the exit URL after saving data: #1262
- [ ] Check the jsPsych trials array for CHS required trials (using custom Lookit version of `initJsPsych`)
- [ ] Add CHS-jsPsych video recording so that videos are stored in our S3 bucket: #1284 
- [ ] Add ability to view responses to jsPsych studies in consent/response areas (integrate jsPsych data names/structure with lookit-api's expectations and/or modify lookit-api data handling pipeline, e.g. frame actions for 'consent' and 'exit' frame/plugin types): #1316
- [ ] Test all the things!

## Documentation:

- [ ] Add a jsPsych page/section in the CHS Lookit docs (with lots of links to the jsPsych docs!)
- [ ] Add/modify docs to go along with any of the more specific changes and new features listed above
- [ ] Update the [Lookit architecture documentation page](https://lookit.readthedocs.io/en/develop/contribute-architecture-overview.html): https://github.com/lookit/lookit-docs/issues/319

# jsPsych phase 2+

This is the list of optional/future requirements for CHS-jsPsych studies. There is a big range in the priority/urgency across these issues, so we should re-order this list as necessary to reflect priorities, and/or split it into requirements for phase 2, 3 ... N.

## Features:

- [ ] CHS-jsPsych video config plugin: #1297
- [ ] CHS-jsPsych video consent plugin: #1295
- [ ] CHS-jsPsych exit survey plugin: #1296 
- [ ] CHS-jsPsych video config quality plugin
- [ ] CHS-jsPsych video assent plugin
- [ ] Pass the child/session info into jsPsych studies (as in protocol generator): #1294
- [ ] Add the ability to pause studies to CHS-jsPsych studies: #1299
- [ ] CHS-jsPsych extension for infant-controlled timing
- [ ] CHS-jsPsych stimuli preview plugin
- [ ] CHS-jsPsych observation plugin
- [ ] CHS-jsPsych change detection plugin
- [ ] CHS-jsPsych calibration plugin

## Documentation:

In addition to the documentation to go along with any of the new features above:

- [ ] How to convert a basic CHS Lookit study protocol into a jsPsych study
- [ ] jsPsych code FAQ/examples
- [ ] Study template examples
